/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    locations: Location;
    services: Service;
    lanes: Lane;
    'rate-cards': RateCard;
    reviews: Review;
    'jobs-stats': JobsStat;
    pages: Page;
    faqs: Faq;
    'content-blocks': ContentBlock;
    guides: Guide;
    posts: Post;
    people: Person;
    media: Media;
    jobs: Job;
    'job-applications': JobApplication;
    leads: Lead;
    'contact-messages': ContactMessage;
    proposals: Proposal;
    'operating-bases': OperatingBase;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    locations: {
      sublocations: 'locations';
    };
  };
  collectionsSelect: {
    locations: LocationsSelect<false> | LocationsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    lanes: LanesSelect<false> | LanesSelect<true>;
    'rate-cards': RateCardsSelect<false> | RateCardsSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    'jobs-stats': JobsStatsSelect<false> | JobsStatsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    'content-blocks': ContentBlocksSelect<false> | ContentBlocksSelect<true>;
    guides: GuidesSelect<false> | GuidesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    people: PeopleSelect<false> | PeopleSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    jobs: JobsSelect<false> | JobsSelect<true>;
    'job-applications': JobApplicationsSelect<false> | JobApplicationsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    'contact-messages': ContactMessagesSelect<false> | ContactMessagesSelect<true>;
    proposals: ProposalsSelect<false> | ProposalsSelect<true>;
    'operating-bases': OperatingBasesSelect<false> | OperatingBasesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'org-profile': OrgProfile;
    'home-content': HomeContent;
  };
  globalsSelect: {
    'org-profile': OrgProfileSelect<false> | OrgProfileSelect<true>;
    'home-content': HomeContentSelect<false> | HomeContentSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Add a city (Type = City) and save it, then add its localities from the Sub-locations panel below.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number;
  name: string;
  /**
   * Lowercase, hyphenated, ASCII. Immutable once published.
   */
  slug: string;
  /**
   * City for a serviceable city, Locality for an area within a city.
   */
  type: 'state' | 'city' | 'locality';
  /**
   * City for a locality; state for a city. Auto-filled when you add from a city.
   */
  parent?: (number | null) | Location;
  /**
   * Optional — auto-filled from the name via Google. Leave blank.
   */
  lat?: number | null;
  lng?: number | null;
  pincodes?: string[] | null;
  populationTier?: ('A' | 'A-S' | 'B') | null;
  /**
   * Gates publication. A city/locality with no completed jobs is not serviceable.
   */
  isServiceable?: boolean | null;
  /**
   * The services you offer in this city — each one gets its own “{Service} in {City}” page. Leave empty to fall back to the automatic data gate.
   */
  servicesOffered?: (number | Service)[] | null;
  /**
   * Background photo for this city’s hero banner (also used as its card thumbnail). Uploaded to Cloudinary. Leave empty to fall back to the built-in /images/hero/cities/<slug>.jpg file.
   */
  heroImage?: (number | null) | Media;
  /**
   * The unique local operational notes (societies, lift rules, gate timings). The section that must exist or the page does not publish.
   */
  editorialNote?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Localities inside this city. “Add new” creates one with the parent (this city) and type filled in for you.
   */
  sublocations?: {
    docs?: (number | Location)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  name: string;
  /**
   * Lowercase, hyphenated, ASCII. Immutable once published.
   */
  slug: string;
  /**
   * Part of the corporate relocation silo (higher ticket).
   */
  isCorporate?: boolean | null;
  summary?: string | null;
  inclusions?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  exclusions?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  typicalDuration?: string | null;
  insuranceTerms?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Descriptive, data-driven. e.g. "MPM crew loading a truck in Powai, Jul 2026".
   */
  alt: string;
  location?: (number | null) | Location;
  capturedOn?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lanes".
 */
export interface Lane {
  id: number;
  /**
   * Display label, e.g. "Delhi to Bengaluru". Slug is derived from the endpoints.
   */
  label?: string | null;
  origin: number | Location;
  destination: number | Location;
  roadKm?: number | null;
  transitDays?: number | null;
  jobCount?: number | null;
  /**
   * e.g. "daily", "3× a week".
   */
  frequency?: string | null;
  /**
   * The overnight-shifting block: load by 8 PM at origin, roll out after no-entry, deliver next morning. Nobody else has this page.
   */
  overnightBlock?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Toll, permit, and state-border notes; seasonal caveats.
   */
  borderNotes?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rate-cards".
 */
export interface RateCard {
  id: number;
  label: string;
  scope: 'service' | 'city' | 'lane';
  service?: (number | null) | Service;
  city?: (number | null) | Location;
  lane?: (number | null) | Lane;
  /**
   * One row per volume band (1BHK, 2BHK, 3BHK, ...).
   */
  bands: {
    band: string;
    base: number;
    perKm?: number | null;
    packing?: number | null;
    insurancePct?: number | null;
    id?: string | null;
  }[];
  validFrom: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  /**
   * Real job reference. A review with no job cannot be published.
   */
  jobRef: string;
  authorName: string;
  rating: number;
  text: string;
  date: string;
  location?: (number | null) | Location;
  service?: (number | null) | Service;
  /**
   * Who verified the job/review.
   */
  verifiedBy?: string | null;
  /**
   * Our public response (required for negative reviews).
   */
  response?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs-stats".
 */
export interface JobsStat {
  id: number;
  /**
   * e.g. "Delhi · Home Shifting · 2026-07".
   */
  label?: string | null;
  location?: (number | null) | Location;
  service?: (number | null) | Service;
  /**
   * YYYY-MM.
   */
  month?: string | null;
  count: number;
  onTimePct?: number | null;
  damagePct?: number | null;
  avgSettlementDays?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Editable copy for the trust, legal and company pages. Blank fields keep the built-in text.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * The page heading (H1).
   */
  title: string;
  /**
   * Which page this entry controls.
   */
  key:
    | 'about'
    | 'terms'
    | 'privacy'
    | 'licences'
    | 'claims'
    | 'insurance'
    | 'protection'
    | 'fraud-check'
    | 'raise-a-complaint';
  /**
   * Small label shown above the heading in the hero.
   */
  eyebrow?: string | null;
  /**
   * The intro paragraph in the hero.
   */
  intro?: string | null;
  /**
   * Main content. Rendered on the prose pages (Terms, Privacy, Licences); leave blank to keep the built-in text.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Meta description (≈150 chars).
   */
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  scope: 'global' | 'city' | 'service' | 'lane';
  city?: (number | null) | Location;
  service?: (number | null) | Service;
  lane?: (number | null) | Lane;
  priority?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-blocks".
 */
export interface ContentBlock {
  id: number;
  label: string;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  scope?: ('global' | 'city' | 'service' | 'lane' | 'locality') | null;
  /**
   * Rotate blocks across pages by this key.
   */
  variantKey?: string | null;
  minUses?: number | null;
  maxUses?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides".
 */
export interface Guide {
  id: number;
  title: string;
  /**
   * Lowercase, hyphenated, ASCII. Immutable once published.
   */
  slug: string;
  excerpt?: string | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  author: number | Person;
  reviewedBy?: (number | null) | Person;
  tags?: string[] | null;
  heroImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people".
 */
export interface Person {
  id: number;
  name: string;
  role: string;
  bio?: string | null;
  photo?: (number | null) | Media;
  /**
   * Credentials shown on guide bylines.
   */
  credentials?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Articles on /blog. Create one, write the body, set a cover, then Publish.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Lowercase, hyphenated, ASCII. Immutable once published.
   */
  slug: string;
  /**
   * One–two sentence summary — shown on the card and used as the meta description.
   */
  excerpt: string;
  category: 'Guides' | 'Pricing' | 'Safety' | 'Packing' | 'Business';
  /**
   * Byline shown on the article.
   */
  author?: string | null;
  /**
   * Shown on the article and used to sort newest-first.
   */
  publishedDate: string;
  /**
   * Cover image (uploads to Cloudinary). Falls back to a stock hero if left empty.
   */
  cover?: (number | null) | Media;
  tags?: string[] | null;
  /**
   * Show this post in the large featured slot at the top of /blog.
   */
  featured?: boolean | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Open roles shown on the careers page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs".
 */
export interface Job {
  id: number;
  title: string;
  /**
   * Lowercase, hyphenated, ASCII. Immutable once published.
   */
  slug: string;
  /**
   * e.g. Operations, Field, Support, Trust.
   */
  team?: string | null;
  employmentType?: ('full-time' | 'part-time' | 'contract' | 'internship') | null;
  location?: string | null;
  /**
   * Show this role as currently open.
   */
  isOpen?: boolean | null;
  /**
   * One or two lines shown on the roles list.
   */
  summary: string;
  /**
   * Optional fuller description (responsibilities, requirements).
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Lower numbers show first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Every careers-form submission lands here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-applications".
 */
export interface JobApplication {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  /**
   * Role the applicant applied for.
   */
  position?: string | null;
  message?: string | null;
  /**
   * A link to a CV or portfolio, if the applicant provided one.
   */
  resumeUrl?: string | null;
  status: 'new' | 'reviewing' | 'shortlisted' | 'rejected' | 'hired';
  assignedTo?: (number | null) | User;
  /**
   * Internal notes on this applicant.
   */
  notes?: string | null;
  sourceIp?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor' | 'ops';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Every quote form and price check lands here. Work them through the status pipeline; filter by "source".
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  phone: string;
  service?: string | null;
  moveSize?: string | null;
  pickup?: string | null;
  dropLocation?: string | null;
  moveDate?: string | null;
  /**
   * How this lead came in.
   */
  source?: ('quote-form' | 'price-check') | null;
  status: 'new' | 'contacted' | 'quoted' | 'won' | 'lost';
  assignedTo?: (number | null) | User;
  /**
   * Internal notes on this lead.
   */
  notes?: string | null;
  sourceIp?: string | null;
  sourcePage?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Every contact-form submission lands here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages".
 */
export interface ContactMessage {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  subject?: string | null;
  message: string;
  status: 'new' | 'handled';
  /**
   * Internal notes.
   */
  notes?: string | null;
  sourceIp?: string | null;
  sourcePage?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * All moving proposals. Create New → fill the form → the Preview & PDF tab shows the downloadable PDF.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proposals".
 */
export interface Proposal {
  id: number;
  status: 'draft' | 'sent' | 'accepted' | 'lost';
  quoteNo?: string | null;
  /**
   * The lead this proposal is for (optional).
   */
  lead?: (number | null) | Lead;
  title?: string | null;
  clientName?: string | null;
  route?: string | null;
  amount?: number | null;
  customer?: {
    name?: string | null;
    phone?: string | null;
    email?: string | null;
  };
  move?: {
    from?: string | null;
    froms?: string | null;
    to?: string | null;
    tos?: string | null;
    date?: string | null;
    house?: ('10 ft' | '12 ft' | '14 ft' | '15 ft' | '16 ft' | '17 ft' | '19 ft') | null;
    dist?: string | null;
    svc?:
      | ('Domestic Household' | 'Local / Within City' | 'Office / Commercial' | 'Vehicle Transport' | 'International')
      | null;
  };
  inventory?:
    | {
        name?: string | null;
        qty?: number | null;
        pack?: ('Standard Wrap' | 'Bubble Wrap' | 'Wooden Crate' | 'Original Box' | 'Blanket Wrap') | null;
        rem?: string | null;
        id?: string | null;
      }[]
    | null;
  charges?:
    | {
        name?: string | null;
        amt?: number | null;
        id?: string | null;
      }[]
    | null;
  pricing?: {
    gstRate?: number | null;
    goodsValue?: number | null;
    /**
     * 0 to drop insurance
     */
    insRate?: number | null;
    validDays?: number | null;
    pay?: string | null;
  };
  /**
   * Use “Title — description” for a bold title + subtext.
   */
  services?:
    | {
        line?: string | null;
        id?: string | null;
      }[]
    | null;
  terms?:
    | {
        line?: string | null;
        id?: string | null;
      }[]
    | null;
  company?: {
    name?: string | null;
    tag?: string | null;
    phone?: string | null;
    mobile?: string | null;
    email?: string | null;
    web?: string | null;
    addr?: string | null;
    gst?: string | null;
    rep?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Dispatch geography only. Feeds the publish gate. Never shown on the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "operating-bases".
 */
export interface OperatingBase {
  id: number;
  label: string;
  address: string;
  /**
   * Optional — auto-filled from the name via Google. Leave blank.
   */
  lat?: number | null;
  lng?: number | null;
  /**
   * Internal licence references.
   */
  licenceIds?: string | null;
  /**
   * Year established.
   */
  established?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'locations';
        value: number | Location;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'lanes';
        value: number | Lane;
      } | null)
    | ({
        relationTo: 'rate-cards';
        value: number | RateCard;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'jobs-stats';
        value: number | JobsStat;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'content-blocks';
        value: number | ContentBlock;
      } | null)
    | ({
        relationTo: 'guides';
        value: number | Guide;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'people';
        value: number | Person;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'jobs';
        value: number | Job;
      } | null)
    | ({
        relationTo: 'job-applications';
        value: number | JobApplication;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'contact-messages';
        value: number | ContactMessage;
      } | null)
    | ({
        relationTo: 'proposals';
        value: number | Proposal;
      } | null)
    | ({
        relationTo: 'operating-bases';
        value: number | OperatingBase;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  type?: T;
  parent?: T;
  lat?: T;
  lng?: T;
  pincodes?: T;
  populationTier?: T;
  isServiceable?: T;
  servicesOffered?: T;
  heroImage?: T;
  editorialNote?: T;
  sublocations?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  isCorporate?: T;
  summary?: T;
  inclusions?:
    | T
    | {
        item?: T;
        id?: T;
      };
  exclusions?:
    | T
    | {
        item?: T;
        id?: T;
      };
  typicalDuration?: T;
  insuranceTerms?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lanes_select".
 */
export interface LanesSelect<T extends boolean = true> {
  label?: T;
  origin?: T;
  destination?: T;
  roadKm?: T;
  transitDays?: T;
  jobCount?: T;
  frequency?: T;
  overnightBlock?: T;
  borderNotes?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rate-cards_select".
 */
export interface RateCardsSelect<T extends boolean = true> {
  label?: T;
  scope?: T;
  service?: T;
  city?: T;
  lane?: T;
  bands?:
    | T
    | {
        band?: T;
        base?: T;
        perKm?: T;
        packing?: T;
        insurancePct?: T;
        id?: T;
      };
  validFrom?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  jobRef?: T;
  authorName?: T;
  rating?: T;
  text?: T;
  date?: T;
  location?: T;
  service?: T;
  verifiedBy?: T;
  response?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs-stats_select".
 */
export interface JobsStatsSelect<T extends boolean = true> {
  label?: T;
  location?: T;
  service?: T;
  month?: T;
  count?: T;
  onTimePct?: T;
  damagePct?: T;
  avgSettlementDays?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  key?: T;
  eyebrow?: T;
  intro?: T;
  body?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  scope?: T;
  city?: T;
  service?: T;
  lane?: T;
  priority?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-blocks_select".
 */
export interface ContentBlocksSelect<T extends boolean = true> {
  label?: T;
  body?: T;
  scope?: T;
  variantKey?: T;
  minUses?: T;
  maxUses?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides_select".
 */
export interface GuidesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  body?: T;
  author?: T;
  reviewedBy?: T;
  tags?: T;
  heroImage?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  category?: T;
  author?: T;
  publishedDate?: T;
  cover?: T;
  tags?: T;
  featured?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people_select".
 */
export interface PeopleSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  bio?: T;
  photo?: T;
  credentials?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  location?: T;
  capturedOn?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs_select".
 */
export interface JobsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  team?: T;
  employmentType?: T;
  location?: T;
  isOpen?: T;
  summary?: T;
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-applications_select".
 */
export interface JobApplicationsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  position?: T;
  message?: T;
  resumeUrl?: T;
  status?: T;
  assignedTo?: T;
  notes?: T;
  sourceIp?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  service?: T;
  moveSize?: T;
  pickup?: T;
  dropLocation?: T;
  moveDate?: T;
  source?: T;
  status?: T;
  assignedTo?: T;
  notes?: T;
  sourceIp?: T;
  sourcePage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages_select".
 */
export interface ContactMessagesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  subject?: T;
  message?: T;
  status?: T;
  notes?: T;
  sourceIp?: T;
  sourcePage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proposals_select".
 */
export interface ProposalsSelect<T extends boolean = true> {
  status?: T;
  quoteNo?: T;
  lead?: T;
  title?: T;
  clientName?: T;
  route?: T;
  amount?: T;
  customer?:
    | T
    | {
        name?: T;
        phone?: T;
        email?: T;
      };
  move?:
    | T
    | {
        from?: T;
        froms?: T;
        to?: T;
        tos?: T;
        date?: T;
        house?: T;
        dist?: T;
        svc?: T;
      };
  inventory?:
    | T
    | {
        name?: T;
        qty?: T;
        pack?: T;
        rem?: T;
        id?: T;
      };
  charges?:
    | T
    | {
        name?: T;
        amt?: T;
        id?: T;
      };
  pricing?:
    | T
    | {
        gstRate?: T;
        goodsValue?: T;
        insRate?: T;
        validDays?: T;
        pay?: T;
      };
  services?:
    | T
    | {
        line?: T;
        id?: T;
      };
  terms?:
    | T
    | {
        line?: T;
        id?: T;
      };
  company?:
    | T
    | {
        name?: T;
        tag?: T;
        phone?: T;
        mobile?: T;
        email?: T;
        web?: T;
        addr?: T;
        gst?: T;
        rep?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "operating-bases_select".
 */
export interface OperatingBasesSelect<T extends boolean = true> {
  label?: T;
  address?: T;
  lat?: T;
  lng?: T;
  licenceIds?: T;
  established?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "org-profile".
 */
export interface OrgProfile {
  id: number;
  brandName: string;
  legalName: string;
  gstin: string;
  cin: string;
  yearsOperating: number;
  insurancePartner?: string | null;
  registeredOffice: string;
  /**
   * Published complaint SLA (e.g. "first response within 24 h").
   */
  complaintSla?: string | null;
  /**
   * Verified profiles: the single GBP, LinkedIn, directory listings.
   */
  sameAs?:
    | {
        url: string;
        id?: string | null;
      }[]
    | null;
  phone?: string | null;
  whatsapp?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-content".
 */
export interface HomeContent {
  id: number;
  taglineLine1?: string | null;
  taglineLine2?: string | null;
  heroSubtext?: string | null;
  servicesHeading?: string | null;
  servicesIntro?: string | null;
  trustHeading?: string | null;
  trustIntro?: string | null;
  statsHeading?: string | null;
  statsIntro?: string | null;
  citiesHeading?: string | null;
  citiesIntro?: string | null;
  faqHeading?: string | null;
  /**
   * Leave empty to use the built-in four pillars.
   */
  pillars?:
    | {
        icon?: ('fixed-quote' | 'verified-crew' | 'claims' | 'insurance' | 'shield-check' | 'check' | 'clock') | null;
        title: string;
        body: string;
        /**
         * Bento position. A good set is one Lead + one Dark + two Default.
         */
        variant?: ('default' | 'lead' | 'dark') | null;
        /**
         * Optional link under the card (e.g. the claims card → /claims).
         */
        link?: {
          label?: string | null;
          href?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "org-profile_select".
 */
export interface OrgProfileSelect<T extends boolean = true> {
  brandName?: T;
  legalName?: T;
  gstin?: T;
  cin?: T;
  yearsOperating?: T;
  insurancePartner?: T;
  registeredOffice?: T;
  complaintSla?: T;
  sameAs?:
    | T
    | {
        url?: T;
        id?: T;
      };
  phone?: T;
  whatsapp?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-content_select".
 */
export interface HomeContentSelect<T extends boolean = true> {
  taglineLine1?: T;
  taglineLine2?: T;
  heroSubtext?: T;
  servicesHeading?: T;
  servicesIntro?: T;
  trustHeading?: T;
  trustIntro?: T;
  statsHeading?: T;
  statsIntro?: T;
  citiesHeading?: T;
  citiesIntro?: T;
  faqHeading?: T;
  pillars?:
    | T
    | {
        icon?: T;
        title?: T;
        body?: T;
        variant?: T;
        link?:
          | T
          | {
              label?: T;
              href?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}